//tag::ref-doc[]
= TriggerTask Source

The TriggerTask app sends a `TaskLaunchRequest` based on a fixed delay, date or
cron expression.  The `TaskLaunchRequest` is used by a tasklauncher-* sink that
will deploy and launch a task.  The only required property for the triggertask
is the --uri which specifies the artifact that will be launched by the
tasklauncher-* that you have selected. The user is also allowed to set the
command line arguments as well as the
http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html[Spring Boot properties]
that are used by the task.

== Input

N/A

== Output

=== Headers:

* `Content-Type: application/octet-stream`

=== Payload:

A  byte array containing the `TaskLaunchRequest`

== Options
The **$$triggertask$$** $$source$$ has the following options:

//tag::configuration-properties[]
$$trigger.cron$$:: $$Cron expression value for the Cron Trigger.$$ *($$String$$, default: `$$<none>$$`)*
$$trigger.date-format$$:: $$Format for the date value.$$ *($$String$$, default: `$$<none>$$`)*
$$trigger.fixed-delay$$:: $$Fixed delay for periodic triggers.$$ *($$Integer$$, default: `$$1$$`)*
$$trigger.initial-delay$$:: $$Initial delay for periodic triggers.$$ *($$Integer$$, default: `$$0$$`)*
$$trigger.max-messages$$:: $$Maximum messages per poll, -1 means infinity.$$ *($$Long$$, default: `$$1$$`)*
$$trigger.source.payload$$:: $$The expression for the payload of the Source module.$$ *($$Expression$$, default: `$$<none>$$`)*
$$trigger.time-unit$$:: $$The TimeUnit to apply to delay values.$$ *($$TimeUnit$$, default: `$$<none>$$`, possible values: `NANOSECONDS`,`MICROSECONDS`,`MILLISECONDS`,`SECONDS`,`MINUTES`,`HOURS`,`DAYS`)*
$$triggertask.application-name$$:: $$The name to be applied to the launched task..$$ *($$String$$, default: `$$<empty string>$$`)*
$$triggertask.command-line-args$$:: $$Space delimited key=value pairs to be used as commandline variables for the task.$$ *($$String$$, default: `$$<empty string>$$`)*
$$triggertask.deployment-properties$$:: $$Comma delimited key=value pairs to be used as deploymentProperties for the task.$$ *($$String$$, default: `$$<empty string>$$`)*
$$triggertask.environment-properties$$:: $$Comma delimited key=value pairs to be used as environmentProperties for the task.$$ *($$String$$, default: `$$<empty string>$$`)*
$$triggertask.uri$$:: $$The uri to the task artifact.$$ *($$String$$, default: `$$<empty string>$$`)*
//end::configuration-properties[]


== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps
```
You can find the corresponding binder based projects here. You can then cd into one one of the folders and
build it:
```
$ ./mvnw clean package
```


=== Examples

```
java -jar trigger_task.jar --triggertask.uri=maven://org.springframework.cloud.task.app:timestamp-task:1.2.0.RELEASE
```

//end::ref-doc[]
